name: publish-ring-wiki

on: [push]

jobs:
  publish-ring-wiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install coscmd
        run: sudo pip install coscmd
      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ring-1252697766
          REGION: ap-beijing
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
      - name: Upload to cos
        run: coscmd upload -r ./ring.wiki/ / --ignore "./.git/*"
